name: Deploy online

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: blog

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          
      - name: Install and build
        run: |
          pnpm i -g @nestjs/cli
          pnpm i
          pnpm build
          cp -rp node_modules ./dist/
          cp .env.example ./dist/

      - name: SCP upload-prod
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST_GOFLASH }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT_GOFLASH }}
          source: "./dist"
          target: "/home/ec2-user/nestjs/community"

      - name: SSH deploy-prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_GOFLASH }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT_GOFLASH }}
          script: |
            cd /home/ec2-user/nestjs/community/dist
            echo "${{ secrets.ENVS_GOFLASH }}" > .env
            pm2 restart ./main.js --name community-api